### ISSUE TITLE
Determine When To Send Emails

### ISSUE THREAD

**Issue by areetaw** [googleinterns/noms#63]
As people add more and more posts, different problems arise with the frequency of email notifications.  Current specifications of the posts include:
- Each **visible** post's time-frame is limited to the current day and must happen from 12:00AM to 11:59PM

Here are possible solutions:

**Send when a new post has been added to a database**
Pros:
- Able to notify users as soon as event has been posted which is great because even club organizers aren't sure how much food is leftover and if they even need people to grab food

Cons:
- When several posts get add, it overcrowds the user's email and they might unsubscribe
- Users will get unneeded notifications because organizers can post about events weeks in the future

**Send emails of all posts that are happening the day at the beginning of the day**
Pros:
- Gathers all posts in a single email which is clean and helpful to a busy college student
- Reminds event organizers to post information about their event earlier

Cons:
- Will require event organizers to know that they will have excess food
- Users might forget when an event is happening 

**Send emails every x hours to cover a certain time span**
Pros:
- Minimizes amount of email notifications that users will get
- Allows event organizers to have more flexibility in when to post

Cons:
- Events will be get missed if an organizer posts an event happening after the email notification checker has already sent out emails for that time span

Feel free to add thoughts and other possible solutions!

**Comment by mrboxtobox** [comment]
Excellent work in listing the different approaches!

**Comment by mirrorkeydev** [comment]
Nice writeup! I do see another possible option, namely:

**Send emails x minutes before event's start (not necessarily when the post is made)**
Pros:
- Emails are seen as immediately actionable to the student, as opposed to an email for something happening hours from now; this could help them make a snap decision about whether or not they can attend and follow through
- Event organizers can post very close to the actual start of the event with no change in how the emails are sent out

Cons: 
- Harder to implement
- Will result in 1 email per post, which might be spammy
- Users might get the notification too late since emails aren't typically seen as an 'instant' medium

I think the **Send emails of all posts that are happening the day at the beginning of the day** option works best though! The newsletter format of emails is familiar to users and I think they appreciate only getting one 'digest' email a day.

**Comment by ubahl** [comment]
Great write up. I would go with *sending emails as the posts come in.* When looking at it from a clubs perspective, our website will mostly be used when there is food at the end of an event, to avoid random people showing up at meetings. With that use case in mind, many clubs won't know if there will be free food at the beginning of the day. 

Another option:

*Have the user specify when they want notifications* (Like Google Groups)
The user can choose between having an email sent 
- For every new post
- Notification grouping (every x minutes)
- At the beginning of each day

Pros: 

- Students can get notifications based on how they plan (ex: if they are more spontaneous with their schedule, they can choose the every new post option)

- We can avoid spamming people

Cons:

- Will take more time to implement
- From the clubs point of view, there isn't a uniform way the students will be receiving posts (there is no guarantee everyone will see it)

Also, I think sending an email x minutes before a post vs. when a post is posted is an interesting debate. It might be best to send as they are posted, because then clubs that are planning for extra food get the word out earlier, and last minute posts are also sent when there is food. Maybe those ones can have a subject line that says [COME NOW] or something.

**Comment by areetaw** [comment]
Thank you so much for everyone's feedback! After discussing and looking over what could add to the complexity of the feature, I've decided to go with a daily digest of **recommend posts** and continuing **sending posts as the post come in**. I will be diving deeper into the idea of recommend posts in the future!
