### ISSUE TITLE
Determine behavior of app when geolocation of post fails

### ISSUE THREAD

**Issue by mirrorkeydev** [googleinterns/noms#71]
When the user enters a location that the geolocator is unable pinpoint a lat/long for, the app currently places the pin at `lat: 0`, `long: 0`, which is just off the western coast of Africa. Obviously, this isn't ideal, so we should see if we can come up with a better solution. If you have any more solutions, please leave them below along with your opinions on how we should move forward!

**Solution: Place pin at college center**

Pros:
- Simple to implement
- User is still able to make the post
- There is still technically one marker per post

Cons:
- Multiple un-placeable events would overlap and not be visible
- Doesn't actually reflect the true location of the event (i.e. may be misleading)
- Doesn't give the user a chance to revise their post to get a valid lat/long (possibly very important to the user that their post appears on the map)

**Solution: Don't place a pin at all**

Pros: 
- Simple to implement
- User is still able to make the post
- Markers on map all correspond to the true location of an event

Cons:
- Doesn't give the user a chance to revise their post to get a valid lat/long (possibly very important to the user that their post appears on the map)
- Might penalize their post's visibility

**Solution: Don't allow the user to make a post until they enter a 'valid' location**

Pros:
- User is given chance to revise their post to get a valid lat/long
- Every post is guaranteed to have a marker on the map

Cons:
- If the geolocation fails because the API doesn't know of the existence of an otherwise perfectly valid location, the user might need to purposely lie about the location in order to event create a post and might resort to something like:
```text
Description: The location says SomeBuilding but this event is actually taking place in OtherBuilding!
```
- If the geolocation fails because the Geolocation API is down, posting becomes impossible

**Comment by areetaw** [comment]
Great breakdown of these solutions! From the student's point of view, additional thoughts include:

- I would be impulsive and hungry so if I saw a pin but it wasn't accurate (**Place pin at college center** solution), I wouldn't bother to check if it was accurate, go to the center location, be very confused, and unsubscribe
- Since the `all-post` section is based on time of the event, it would still bring up the post and I would be able to see with the accurate location

To see if users feel that pin on a map is very important, we can conduct a user research with club organizers!

Overall, I would like to combine the **Don't place a pin at all**  and **Don't allow the user to make a post until they enter a 'valid' location** by implementing: 

**Check in with user to let them know their location isn't valid and if location can not be valid, add post without placing pin** 

Pros:

- User is given chance to revise their post to get a valid lat/long (especially if it's a typo)
- User is still able to make the post
- Markers on map all correspond to the true location of an event
- User will understand that there will be not be a pin
- Won't have multiple un-placeable events would overlap and not be visible

Cons:

- Might penalize their post's visibility
- Harder to implement

**Comment by ubahl** [comment]
Great write up! I agree, having the pins be accurate is very important. Here is an idea that builds on **don't allow the user to make a post until they enter a 'valid' location**:

We can have the student enter a location, and on submit of the button, check if it is a valid location (relates to #52 of checking the user's inputs before submitting). If it is not, we can offer the option of **placing a pin.**

**Placing a pin**:
Idea: present a map of campus and have the user click on where the event would be. Store this as the lat and lng, along with the text they entered for the post location.

Pros:

- An interesting solution: user input on a map is something we haven't tackled!
- Many college locations are hard to find on with a text query
- Can also be used to confirm the inputted location
- Most accurate way to specify location to avoid confused students

Cons:

- May take longer to implement
- Adds more complexity to creating a post

Also if we do decide to go this direction, I would love to help out! This sounds fun

**Comment by mirrorkeydev** [comment]
Thanks for the suggestions all!

I think the approach I'm going to take (for now) is @areetaw's, and have @ubahl's as a stretch goal.
