### ISSUE TITLE
Address issue where users are confused that they can't see posts made for a different day

### ISSUE THREAD

**Issue by mirrorkeydev** [googleinterns/noms#91]
## User feedback
>I know this is by design, but it still looks like a bug to users when they are unable to see an event (unless it's for today) after they post it.

## Possible ways we could address this

**Notify user after posting that their post made for a different day will only be visible on that day**
`Thanks for submitting! Students will see your post on [Date]`
Pros:
- User understands that their post will appear on that day
- Would be easy to integrate into the existing 'Your post has been submitted' popup

Cons:
- User only finds this out after making their first post, and it's possible that this information might have influenced their decision in posting early (e.g. hoping people might learn about the event days earlier)

**Pop up/alert this information in the modal upon picking a date in the future**
`Tip: If you're making a post for a future date, it won't appear in the feed until that day`
Pros:
- User understands that their post will appear on that day
- User is able to change their mind about posting if this information is a deal-breaker

Cons:
- Might make the modal look busier

**Allow users to see really far into the future (i.e. remove the 1-day limit)**
Pros:
- Users will always be able to see their new event if they scroll (very far) down
- Other users might benefit by being able to see tomorrow's events

Cons:
- Other users might not appreciate being able to see tomorrow's events (research would need to be done)
- People might be incentivized to make posts for future dates, which could lead to 'rotting' future information if they decide to cancel the week before the event or reschedule (since they can't delete the post, they either have false information or duplicate information)

Feel free to leave more ideas below!

**Comment by areetaw** [comment]
Great write up! A combination of both **Pop up/alert this information in the modal upon picking a date in the future** and **Notify user after posting that their post made for a different day will only be visible on that day** makes the most sense to me because it would be really clear to the user what's happening. It would take away the con of user only finds out after making the post! For the making the modal look busier, I believe it's fine as long as it's a different color from the red error messages for form validation.
